# -*- coding: utf-8 -*-
"""Code MP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sGEpkQtE_xHjc8oMMjTtWvsjS-mu0vJZ

# 🌦️ Open-Meteo Flood & Weather API Analysis
This notebook covers:
- Data collection using Open-Meteo APIs
- EDA for rainfall, temperature, wind, and river discharge
- Feature engineering for CNN–LSTM flood prediction model.
"""


# """## 1️⃣ Data Collection — Open-Meteo Weather API"""

import openmeteo_requests
import pandas as pd
import requests_cache
from retry_requests import retry

cache_session = requests_cache.CachedSession('.cache', expire_after=-1)
retry_session = retry(cache_session, retries=5, backoff_factor=0.2)
openmeteo = openmeteo_requests.Client(session=retry_session)

url = "https://archive-api.open-meteo.com/v1/archive"
locations = [
    {"name": "Petaling", "latitude": 3.107260, "longitude": 101.606710},
    {"name": "Klang", "latitude": 3.043092, "longitude": 101.441392}
]

common_params = {
    "start_date": "2010-01-01",
    "end_date": "2025-12-31",
    "daily": ["rain_sum","precipitation_sum","temperature_2m_mean","wind_speed_10m_max","wind_gusts_10m_max"],
    "timezone": "Asia/Kuala_Lumpur"
}

all_daily = []
for loc in locations:
    params = common_params | {"latitude": loc["latitude"], "longitude": loc["longitude"]}
    responses = openmeteo.weather_api(url, params=params)
    response = responses[0]
    daily = response.Daily()
    daily_data = {
        "date": pd.date_range(start=pd.to_datetime(daily.Time(), unit='s', utc=True),
                              end=pd.to_datetime(daily.TimeEnd(), unit='s', utc=True),
                              freq=pd.Timedelta(seconds=daily.Interval()), inclusive='left'),
        "rain_sum_mm": daily.Variables(0).ValuesAsNumpy(),
        "precipitation_sum_mm": daily.Variables(1).ValuesAsNumpy(),
        "temperature_mean_°C": daily.Variables(2).ValuesAsNumpy(),
        "wind_speed_max_mps": daily.Variables(3).ValuesAsNumpy(),
        "wind_gust_max_mps": daily.Variables(4).ValuesAsNumpy(),
        "location": loc["name"]
    }
    all_daily.append(pd.DataFrame(daily_data))

daily_df = pd.concat(all_daily, ignore_index=True)
print(f"✅ Combined records: {len(daily_df)}")
daily_df.head()

"""## 2️⃣ Data Collection — Open-Meteo Flood API"""

url_flood = "https://flood-api.open-meteo.com/v1/flood"
common_params = {
    "start_date": "2010-01-01",
    "end_date": "2025-12-31",
    "daily": ["river_discharge"],
    "timezone": "Asia/Kuala_Lumpur"
}

all_discharge = []
for loc in locations:
    params = common_params | {"latitude": loc["latitude"], "longitude": loc["longitude"]}
    responses = openmeteo.weather_api(url_flood, params=params)
    response = responses[0]
    daily = response.Daily()
    discharge_data = {
        "date": pd.date_range(start=pd.to_datetime(daily.Time(), unit='s', utc=True),
                              end=pd.to_datetime(daily.TimeEnd(), unit='s', utc=True),
                              freq=pd.Timedelta(seconds=daily.Interval()), inclusive='left'),
        "river_discharge_m3s": daily.Variables(0).ValuesAsNumpy(),
        "location": loc["name"]
    }
    all_discharge.append(pd.DataFrame(discharge_data))

discharge_df = pd.concat(all_discharge, ignore_index=True)
print(f"✅ Combined records: {len(discharge_df)}")
discharge_df.head()

# """## 3️⃣.1️⃣ Exploratory Data Analysis (EDA) - Flood"""

# # ============================================================
# # 📊 Exploratory Data Analysis (EDA)
# # Dataset: Open-Meteo Flood API - River Discharge (Klang & Petaling, 2020–2025)
# # ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================
# 6️⃣ EXTREME EVENTS DETECTION
# ============================================================

# Define extreme discharge threshold (e.g., top 5% highest)
threshold = discharge_df["river_discharge_m3s"].quantile(0.95)
extreme_events = discharge_df[discharge_df["river_discharge_m3s"] >= threshold]

# ============================================================
# 7️⃣ SUMMARY
# ============================================================

print("\n✅ EDA Summary for River Discharge (2020–2025)")
print(f"• Total records: {len(discharge_df)}")
print(f"• Date range: {discharge_df['date'].min()} → {discharge_df['date'].max()}")
print(f"• Locations: {', '.join(discharge_df['location'].unique())}")
print(f"• Mean discharge: {discharge_df['river_discharge_m3s'].mean():.2f} m³/s")
print(f"• Max discharge: {discharge_df['river_discharge_m3s'].max():.2f} m³/s")
print(f"• Extreme discharge threshold (95th percentile): {threshold:.2f} m³/s")
print(f"• Number of extreme days: {len(extreme_events)}")

print("\n🎯 EDA completed successfully.")


temp_col = next((c for c in daily_df.columns if "temp" in c.lower()), None)


"""## 3️⃣.2️⃣ Exploratory Data Analysis (EDA) - Temporal"""

# # ============================================================
# # 📊 Exploratory Data Analysis (EDA)
# # Dataset: Open-Meteo Daily Weather Data (Klang & Petaling, 2025)
# # ============================================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np



# ============================================================
# 9️⃣ RAIN/NON-RAIN DAYS — CLASS IMBALANCE
# ============================================================

daily_df["rain_label"] = np.where(daily_df["rain_sum_mm"] > 0, "Rain", "No Rain")
# sns.countplot(data=daily_df, x="rain_label", hue="location", palette="Set2")
# plt.title("Rain vs No Rain Days (Klang & Petaling, 2025)")
# plt.xlabel("")
# plt.ylabel("Count")
# plt.tight_layout()
# plt.show()

rain_ratio = daily_df["rain_label"].value_counts(normalize=True) * 100
print("\n🌧️ Rain Day Proportion (%):")
print(rain_ratio.round(2))

# ============================================================
# 🔟 SUMMARY
# ============================================================

print("\n✅ EDA Summary (2025):")
print(f"• Date Range: {daily_df['date'].min().date()} → {daily_df['date'].max().date()}")
print(f"• Locations Analyzed: {daily_df['location'].unique().tolist()}")
print(f"• Mean Daily Rainfall: {daily_df['rain_sum_mm'].mean():.2f} mm")
print(f"• Days with Rain: {(daily_df['rain_sum_mm'] > 0).sum()} / {len(daily_df)} days")
print(f"• Mean Temperature: {daily_df[temp_col].mean():.2f} °C" if temp_col else "")
print(f"• Average Wind Speed: {daily_df['wind_speed_max_mps'].mean():.2f} m/s" if 'wind_speed_max_mps' in daily_df.columns else "")
print("\n🎯 EDA completed successfully for Klang & Petaling (2025).")

# # CODE ORIGIN
import seaborn as sns
import matplotlib.pyplot as plt



# """## 4️⃣.1️⃣ Feature Engineering for CNN–LSTM (Hydrological - Flood)"""

# ============================================================
# 🌊 Feature Engineering — Open-Meteo Flood (discharge_df)
# ============================================================

import pandas as pd
import numpy as np

# --- Convert and sort ---
discharge_df["date"] = pd.to_datetime(discharge_df["date"])
discharge_df = discharge_df.sort_values(["location", "date"]).reset_index(drop=True)

print(f"\n✅ Discharge dataset loaded: {len(discharge_df)} records")
print(f"Date range: {discharge_df['date'].min()} → {discharge_df['date'].max()}")
print(f"Locations: {discharge_df['location'].unique()}")

# ============================================================
# 1️⃣ HYDROLOGICAL FEATURES
# ============================================================

# Lag features
for lag in [1, 3, 7]:
    discharge_df[f"discharge_lag_{lag}d"] = discharge_df.groupby("location")["river_discharge_m3s"].shift(lag)

# Rolling averages and cumulative sums
discharge_df["discharge_rolling_3d"] = discharge_df.groupby("location")["river_discharge_m3s"].transform(lambda x: x.rolling(3).mean())
discharge_df["discharge_cum_7d"] = discharge_df.groupby("location")["river_discharge_m3s"].transform(lambda x: x.rolling(7).sum())

# Discharge rate of change
discharge_df["discharge_delta_1d"] = discharge_df.groupby("location")["river_discharge_m3s"].diff(1)
discharge_df["discharge_change_pct"] = discharge_df.groupby("location")["river_discharge_m3s"].pct_change()

# Anomaly detection (deviation from 3-day mean)
discharge_df["discharge_anomaly"] = discharge_df["river_discharge_m3s"] - discharge_df["discharge_rolling_3d"]

# ============================================================
# 2️⃣ EXTREME RIVER DISCHARGE EVENT DETECTION
# ============================================================

# Compute extreme discharge threshold (e.g., top 5%)
flood_threshold = discharge_df["river_discharge_m3s"].quantile(0.95)

# Flag for extreme floods
discharge_df["is_extreme_river_discharge"] = (discharge_df["river_discharge_m3s"] >= flood_threshold).astype(int)

# Z-score normalization to highlight anomalies
discharge_df["discharge_zscore"] = (
    (discharge_df["river_discharge_m3s"] - discharge_df["river_discharge_m3s"].mean())
    / discharge_df["river_discharge_m3s"].std()
)

# Count extreme days
n_extreme = discharge_df["is_extreme_river_discharge"].sum()
print(f"\n⚠️ Extreme Flood Events Detected (≥95th percentile, ≥{flood_threshold:.2f} m³/s): {n_extreme} days")

# Preview top extreme events
# display(
#     discharge_df[discharge_df["is_extreme_river_discharge"] == 1]
#     .sort_values(by="river_discharge_m3s", ascending=False)
#     .head(10)
# )

# ============================================================
# 3️⃣ TIME FEATURES (for model alignment)
# ============================================================

discharge_df["dayofyear"] = discharge_df["date"].dt.dayofyear
discharge_df["month"] = discharge_df["date"].dt.month
discharge_df["weekday"] = discharge_df["date"].dt.weekday
discharge_df["is_weekend"] = discharge_df["weekday"].isin([5, 6]).astype(int)

# ============================================================
# 4️⃣ CLEANING
# ============================================================

# Forward-fill and backward-fill missing data per location
discharge_df = discharge_df.groupby("location").apply(lambda g: g.ffill().bfill()).reset_index(drop=True)

# Drop any remaining missing discharge
discharge_df = discharge_df.dropna(subset=["river_discharge_m3s"])

print("\n✅ Flood feature engineering completed successfully.")
print(f"Final shape: {discharge_df.shape}")
print(f"New columns added: {[c for c in discharge_df.columns if 'discharge_' in c and c not in ['river_discharge_m3s']]}")



"""## 4️⃣.2️⃣ Feature Engineering for CNN–LSTM (Meteorological - Temporal)"""

# ============================================================
# 🌦️ Feature Engineering — Open-Meteo Weather (daily_df)
# ============================================================

import pandas as pd
import numpy as np

# --- Convert and sort date ---
daily_df["date"] = pd.to_datetime(daily_df["date"])
daily_df = daily_df.sort_values(["location", "date"]).reset_index(drop=True)

print(f"\n✅ Weather dataset loaded: {len(daily_df)} records")
print(f"Date range: {daily_df['date'].min()} → {daily_df['date'].max()}")
print(f"Locations: {daily_df['location'].unique()}")

# ============================================================
# 1️⃣ TEMPORAL FEATURES
# ============================================================

# Lag features for rainfall, temperature, and wind
for lag in [1, 3, 7]:
    daily_df[f"rain_lag_{lag}d"] = daily_df.groupby("location")["rain_sum_mm"].shift(lag)
    daily_df[f"temp_lag_{lag}d"] = daily_df.groupby("location")["temperature_mean_°C"].shift(lag)

# Rolling stats
daily_df["rain_rolling_3d"] = daily_df.groupby("location")["rain_sum_mm"].transform(lambda x: x.rolling(3).mean())
daily_df["rain_cum_7d"] = daily_df.groupby("location")["rain_sum_mm"].transform(lambda x: x.rolling(7).sum())

# Calendar features
daily_df["dayofyear"] = daily_df["date"].dt.dayofyear
daily_df["month"] = daily_df["date"].dt.month
daily_df["weekday"] = daily_df["date"].dt.weekday
daily_df["is_weekend"] = daily_df["weekday"].isin([5, 6]).astype(int)

# ============================================================
# 2️⃣ METEOROLOGICAL FEATURES
# ============================================================

# Combined atmospheric index
daily_df["atmo_index"] = (
    daily_df["rain_sum_mm"].fillna(0)
    + daily_df["precipitation_sum_mm"].fillna(0)
    + (daily_df["wind_speed_max_mps"].fillna(0) * 0.5)
)

# Air-water interaction proxy
daily_df["temp_wind_interaction"] = (
    daily_df["temperature_mean_°C"].fillna(0)
    * daily_df["wind_speed_max_mps"].fillna(0)
)

# ============================================================
# 3️⃣ EXTREME WEATHER EVENT DETECTION
# ============================================================

# Define thresholds (95th percentile)
rain_threshold = daily_df["rain_sum_mm"].quantile(0.95)
temp_threshold = daily_df["temperature_mean_°C"].quantile(0.95)
wind_threshold = daily_df["wind_speed_max_mps"].quantile(0.95)

# Create binary flags for extremes
daily_df["extreme_rain"] = (daily_df["rain_sum_mm"] >= rain_threshold).astype(int)
daily_df["extreme_temp"] = (daily_df["temperature_mean_°C"] >= temp_threshold).astype(int)
daily_df["extreme_wind"] = (daily_df["wind_speed_max_mps"] >= wind_threshold).astype(int)

# Composite extreme weather flag
daily_df["is_extreme_weather"] = (
    (daily_df["extreme_rain"] + daily_df["extreme_temp"] + daily_df["extreme_wind"]) > 0
).astype(int)

# Z-scores for anomaly intensity
for col in ["rain_sum_mm", "temperature_mean_°C", "wind_speed_max_mps"]:
    z_col = col.replace("_mm", "_zscore").replace("_°C", "_zscore").replace("_mps", "_zscore")
    daily_df[z_col] = (daily_df[col] - daily_df[col].mean()) / daily_df[col].std()

# Print summary
print("\n⚠️ Extreme Weather Detection Summary:")
print(f"Rainfall ≥ {rain_threshold:.2f} mm → {daily_df['extreme_rain'].sum()} days")
print(f"Temperature ≥ {temp_threshold:.2f}°C → {daily_df['extreme_temp'].sum()} days")
print(f"Wind Speed ≥ {wind_threshold:.2f} m/s → {daily_df['extreme_wind'].sum()} days")
print(f"Total Extreme Weather Days: {daily_df['is_extreme_weather'].sum()}")

# Preview top 10 extreme events
# display(
#     daily_df[daily_df["is_extreme_weather"] == 1]
#     .sort_values(by=["rain_sum_mm", "temperature_mean_°C", "wind_speed_max_mps"], ascending=False)
#     .head(10)
# )

# ============================================================
# 4️⃣ CLEANING
# ============================================================

# Fill missing by location
daily_df = daily_df.groupby("location").apply(lambda g: g.ffill().bfill()).reset_index(drop=True)
daily_df = daily_df.dropna(subset=["rain_sum_mm", "temperature_mean_°C"])

print("\n✅ Weather feature engineering completed successfully.")
print(f"Final shape: {daily_df.shape}")
print(f"New columns added: {[c for c in daily_df.columns if 'lag' in c or 'rolling' in c or 'extreme' in c or 'zscore' in c or 'atmo' in c]}")



"""## 5️⃣ CNN–LSTM Model Training & Evaluation"""

# ============================================================
    # 🤖 CNN–LSTM Model Training & Evaluation
    # Datasets: Open-Meteo Weather (daily_df) + Flood (discharge_df)
    # Includes Extreme Event & Z-Score Features
    # ============================================================

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import class_weight
from sklearn.metrics import (
        accuracy_score, precision_score, recall_score, f1_score,
        confusion_matrix, classification_report
    )
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Conv1D, MaxPooling1D, Dropout, Dense
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import seaborn as sns

    # ============================================================
    # 1️⃣ DATA MERGING — Weather + Flood
    # ============================================================

    # Merge weather and discharge features on date + location
merged = pd.merge(
        daily_df,
        discharge_df,
        on=["date", "location"],
        suffixes=("_weather", "_flood")
    ).dropna(subset=["river_discharge_m3s"])

print(f"\n✅ Merged dataset created: {len(merged)} records")
print(f"Date range: {merged['date'].min()} → {merged['date'].max()}")
print(f"Locations: {merged['location'].unique()}")

    # ============================================================
    # 2️⃣ FEATURE SELECTION
    # ============================================================

feature_cols = [
        # Weather variables
        "rain_sum_mm", "precipitation_sum_mm", "temperature_mean_°C",
        "wind_speed_max_mps", "wind_gust_max_mps", "atmo_index",
        "temp_wind_interaction", "rain_lag_1d", "rain_lag_3d",
        "rain_rolling_3d", "rain_cum_7d",

        # Z-score & extreme weather features
        "rain_sum_zscore", "temperature_mean_zscore", "wind_speed_zscore",
        "is_extreme_weather",

        # Flood variables
        "discharge_lag_1d", "discharge_lag_3d", "discharge_rolling_3d",
        "discharge_cum_7d", "discharge_delta_1d", "discharge_anomaly",
        "discharge_zscore",

        # Time features
        "dayofyear_flood", "month_flood", "weekday_flood"
    ]

    # Ensure columns exist
feature_cols = [c for c in feature_cols if c in merged.columns]
print(f"\n🧩 Features used ({len(feature_cols)}): {feature_cols}")

    # ============================================================
    # 3️⃣ TARGET VARIABLE — Extreme Flood Flag
    # ============================================================

if "is_extreme_flood" in merged.columns:
        merged["flood_label"] = merged["is_extreme_flood"]
        print("\n🌊 Using `is_extreme_flood` as target variable.")
else:
        threshold = merged["river_discharge_m3s"].quantile(0.8)
        merged["flood_label"] = (merged["river_discharge_m3s"] >= threshold).astype(int)
        print(f"\n⚙️ No explicit extreme flag found. Using threshold ≥ {threshold:.2f} m³/s")

print(f"Flood event ratio: {merged['flood_label'].mean():.3f}")

    # ============================================================
    # 4️⃣ SCALING & SEQUENCE CREATION
    # ============================================================

scaler = StandardScaler()
scaled_features = scaler.fit_transform(merged[feature_cols])
scaled_df = pd.DataFrame(scaled_features, columns=feature_cols)
scaled_df["flood_label"] = merged["flood_label"].values

    # Function to create time-series sequences
def create_sequences(data, labels, lookback=7):
        X, y = [], []
        for i in range(lookback, len(data)):
            X.append(data[i - lookback:i])
            y.append(labels[i])
        return np.array(X), np.array(y)

    # Create sequences
X, y = create_sequences(
        scaled_df[feature_cols].values,
        scaled_df["flood_label"].values,
        lookback=7
    )

    # Split into train/test (no shuffle — preserve time order)
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, shuffle=False
    )

print(f"\n🧠 X_train shape: {X_train.shape}")
print(f"🧠 y_train shape: {y_train.shape}")
print(f"Flood ratio in training: {y_train.mean():.3f}")

    # ============================================================
    # 5️⃣ MODEL DEFINITION — CNN–LSTM
    # ============================================================

model = Sequential([
        Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])),
        MaxPooling1D(pool_size=2),
        Dropout(0.3),
        LSTM(64, return_sequences=False),
        Dense(32, activation='relu'),
        Dropout(0.3),
        Dense(1, activation='sigmoid')
    ])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

    # ============================================================
    # 6️⃣ MODEL TRAINING (Weighted for Flood Class)
    # ============================================================

    # Handle class imbalance
weights = class_weight.compute_class_weight(
        class_weight='balanced',
        classes=np.unique(y_train),
        y=y_train
    )
class_weights = {0: weights[0], 1: weights[1]}
print("\n⚖️ Class Weights:", class_weights)

es = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history = model.fit(
        X_train, y_train,
        validation_split=0.2,
        epochs=60,
        batch_size=16,
        class_weight=class_weights,
        callbacks=[es],
        verbose=1
    )

    # ============================================================
    # 7️⃣ PERFORMANCE EVALUATION
    # ============================================================

y_pred_prob = model.predict(X_test)
# Slightly lower threshold to favor flood recall
y_pred = (y_pred_prob > 0.3).astype(int)

    # Metrics
acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("\n📊 Model Performance Metrics (threshold=0.3):")
print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1-Score:  {f1:.4f}")

# ============================================================
# 8️⃣ CONFUSION MATRIX & REPORT
# ============================================================

cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(cm,
                    index=['Actual_NoFlood', 'Actual_Flood'],
                    columns=['Predicted_NoFlood', 'Predicted_Flood'])

# # Heatmap
# plt.figure(figsize=(5,4))
# sns.heatmap(cm_df, annot=True, fmt='d', cmap='Blues')
# plt.title("Confusion Matrix — CNN-LSTM Flood Detection (Extreme Flag)")
# plt.ylabel("Actual")
# plt.xlabel("Predicted")
# plt.show()

print("\n🧾 Confusion Matrix (Table Format):")
# display(cm_df)

    # Detailed report
print("\nDetailed Classification Report:\n")
print(classification_report(y_test, y_pred, target_names=['No Flood','Flood']))

# # ============================================================
# # 9️⃣ TRAINING VISUALIZATION
# # ============================================================

# plt.figure(figsize=(10,4))
# plt.plot(history.history['loss'], label='Train Loss')
# plt.plot(history.history['val_loss'], label='Validation Loss')
# plt.title('Model Training Loss (CNN–LSTM)')
# plt.xlabel('Epoch')
# plt.ylabel('Binary Crossentropy')
# plt.legend()
# plt.show()

# plt.figure(figsize=(10,4))
# plt.plot(history.history['accuracy'], label='Train Accuracy')
# plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
# plt.title('Model Accuracy Over Epochs (CNN–LSTM)')
# plt.xlabel('Epoch')
# plt.ylabel('Accuracy')
# plt.legend()
# plt.show()

"""70% Train, 15% Val, 15% Test"""

# ============================================================
# 🤖 CNN–LSTM Model Training & Evaluation (70/15/15 Split)
# Datasets: Open-Meteo Weather (daily_df) + Flood (discharge_df)
# ============================================================

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.utils import class_weight
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report
)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Conv1D, MaxPooling1D, Dropout, Dense
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================
# 1️⃣ DATA MERGING — Weather + Flood
# ============================================================

merged = pd.merge(
    daily_df,
    discharge_df,
    on=["date", "location"],
    suffixes=("_weather", "_flood")
).dropna(subset=["river_discharge_m3s"])

print(f"\n✅ Merged dataset created: {len(merged)} records")
print(f"Date range: {merged['date'].min()} → {merged['date'].max()}")
print(f"Locations: {merged['location'].unique()}")

# ============================================================
# 2️⃣ FEATURE SELECTION
# ============================================================

feature_cols = [
    "rain_sum_mm", "precipitation_sum_mm", "temperature_mean_°C",
    "wind_speed_max_mps", "wind_gust_max_mps", "atmo_index",
    "temp_wind_interaction", "rain_lag_1d", "rain_lag_3d",
    "rain_rolling_3d", "rain_cum_7d",
    "rain_sum_zscore", "temperature_mean_zscore", "wind_speed_zscore",
    "is_extreme_weather",
    "discharge_lag_1d", "discharge_lag_3d", "discharge_rolling_3d",
    "discharge_cum_7d", "discharge_delta_1d", "discharge_anomaly",
    "discharge_zscore",
    "dayofyear_flood", "month_flood", "weekday_flood"
]

feature_cols = [c for c in feature_cols if c in merged.columns]
print(f"\n🧩 Features used ({len(feature_cols)}): {feature_cols}")

# ============================================================
# 3️⃣ TARGET VARIABLE — Extreme Flood or Threshold
# ============================================================

if "is_extreme_flood" in merged.columns:
    merged["flood_label"] = merged["is_extreme_flood"]
    print("\n🌊 Using `is_extreme_flood` as target.")
else:
    threshold = merged["river_discharge_m3s"].quantile(0.8)
    merged["flood_label"] = (merged["river_discharge_m3s"] >= threshold).astype(int)
    print(f"\n⚙️ Threshold for extreme flood: ≥ {threshold:.2f} m³/s")

print(f"Flood ratio: {merged['flood_label'].mean():.3f}")

# ============================================================
# 4️⃣ SCALING + SEQUENCE CREATION
# ============================================================

scaler = StandardScaler()
scaled_features = scaler.fit_transform(merged[feature_cols])
scaled_df = pd.DataFrame(scaled_features, columns=feature_cols)
scaled_df["flood_label"] = merged["flood_label"].values

def create_sequences(data, labels, lookback=7):
    X, y = [], []
    for i in range(lookback, len(data)):
        X.append(data[i-lookback:i])
        y.append(labels[i])
    return np.array(X), np.array(y)

X, y = create_sequences(
    scaled_df[feature_cols].values,
    scaled_df["flood_label"].values,
    lookback=7
)

print(f"\n📦 Sequence dataset size: {X.shape}, labels: {y.shape}")

# ============================================================
# 5️⃣ TIME-SERIES SPLIT → 70% Train, 15% Val, 15% Test
# ============================================================

total = len(X)
train_end = int(total * 0.70)
val_end = int(total * 0.85)

X_train, y_train = X[:train_end], y[:train_end]
X_val,   y_val   = X[train_end:val_end], y[train_end:val_end]
X_test,  y_test  = X[val_end:], y[val_end:]

print("\n📌 Time-series split:")
print(f"Train: {X_train.shape} ({len(X_train)/total:.1%})")
print(f"Val:   {X_val.shape} ({len(X_val)/total:.1%})")
print(f"Test:  {X_test.shape} ({len(X_test)/total:.1%})")

# ============================================================
# 6️⃣ MODEL DEFINITION — CNN–LSTM
# ============================================================

model = Sequential([
    Conv1D(64, kernel_size=2, activation='relu',
           input_shape=(X_train.shape[1], X_train.shape[2])),
    MaxPooling1D(2),
    Dropout(0.3),

    LSTM(64, return_sequences=False),
    Dense(32, activation='relu'),
    Dropout(0.3),

    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

# Class imbalance handling
weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)
class_weights = {0: weights[0], 1: weights[1]}

print("\n⚖️ Class weights:", class_weights)

# Train with explicit validation data
es = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=60,
    batch_size=16,
    class_weight=class_weights,
    callbacks=[es],
    verbose=1
)

# ============================================================
# 7️⃣ EVALUATION
# ============================================================

y_prob = model.predict(X_test)
y_pred = (y_prob > 0.3).astype(int)

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("\n📊 Final Model Performance:")
print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1-score:  {f1:.4f}")

# ============================================================
# 8️⃣ CONFUSION MATRIX + CLASSIFICATION REPORT
# ============================================================

cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(cm,
                     index=['Actual_NoFlood', 'Actual_Flood'],
                     columns=['Pred_NoFlood', 'Pred_Flood'])

# plt.figure(figsize=(5,4))
# sns.heatmap(cm_df, annot=True, cmap="Blues", fmt="d")
# plt.title("Confusion Matrix — CNN–LSTM")
# plt.show()

print("\n🧾 Classification Report:")
print(classification_report(y_test, y_pred, target_names=["No Flood", "Flood"]))

